### ISSUE TITLE
Replace apt with package module

### ISSUE THREAD

**Issue by daFritz84** [nickjj/ansible-acme-sh#13]
I would recommend replacing the call to the `apt` module with the more modern `package` module [Link](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html).

**Ratio:** 
Right now, only Debian based distributions are supported. This is mainly caused by the use of the `apt` task installing the required dependencies. Replacing this very first task would open up this role for other distributions as well.

In fact, I tested the role successfully with CentOS Stream by simply deleteing the `apt` task in `main.yml`

**Comment by nickjj** [comment]
Hi,

Supporting other distros comes with a set of responsibilities that I'd rather not take on at the moment, since I personally don't use CentOS in production it would be difficult to offer support for that.

It's interesting to hear the role works with just this change tho.

**Comment by daFritz84** [comment]
Well acme.sh itself supports other distros. So no worries here.
I understand that you rather not support other distros considering the necessary effort in testing and support. But would you accept a pull request replacing `apt` with `package`?

**Comment by nickjj** [comment]
As long as it still works on Debian and Ubuntu and the PR doesn't mention officially supporting other distros (such as in the meta.yml and readme) I'm open for it.

**Comment by daFritz84** [comment]
Well, silly me. It seems that this is done already. The issue was resolved by commit e9fade4a5df0b49293e86417da3ac4cb924b6a4a
I was fooled by `ansible-galaxy`; Version 1.0.0 in ansible-galaxy does not have this fix. 

Is it possible to push a new release to ansible-galaxy? 😊

**Comment by nickjj** [comment]
Haha oh yeah. For some reason May 2020 feels like it was 100 years ago. Totally forgot about merging that.

I'll cut a new release today.

**Comment by nickjj** [comment]
Ok, it's on the Galaxy as v1.1.0.

Although the role's score dropped from 5 to 2.9 because of some really silly linting rules enforced nowadays.

**Comment by daFritz84** [comment]
Thanks, much appreciated!
